const viewer=document.querySelector('#avatar-niko');viewer.addEventListener('load',()=>{const materials=viewer.model.materials;for(let material of materials){material.setAlphaMode('OPAQUE')}
console.log("¡Avatar cargado con el motor de Google y físicas perfectas!")});document.addEventListener("DOMContentLoaded",()=>{const miBoton=document.getElementById("mi-boton-coffee");miBoton.addEventListener("click",(event)=>{event.preventDefault();const botonBMC=document.getElementById("bmc-wbtn");if(botonBMC){botonBMC.click()}else{console.warn("No se encontró el widget de BMC. Revisa si el ID original cambió.")}})});const scriptURL='https://script.google.com/macros/s/AKfycbxVdjLIHnjMDu7KRwo1QzhdDfqfkAAMsL30TZqwEmvU1sBsBKbOvcVvBiECmWmnB-Tfuw/exec';const form=document.getElementById('mensajeAnonimo');const mensajeExito=document.getElementById('mensajeExito');if(form){form.addEventListener('submit',e=>{e.preventDefault();fetch(scriptURL,{method:'POST',body:new URLSearchParams(new FormData(form))}).then(response=>{document.body.classList.add('formulario-enviado');form.reset();const miTextArea=document.getElementById('mensaje');if(miTextArea){miTextArea.value=''}}).catch(error=>console.error('Error en el envío:',error))})}
$(document).ready(function(){$('#buttonForm').on('click',function(){let $boton=$(this);$boton.addClass('mainGrid__message--sendpulsado');$('#buttonLoading').addClass('buttonLoading');$('#textbutton').addClass('none')})});document.addEventListener('DOMContentLoaded',()=>{const themeButton=document.getElementById('themeButton');if(themeButton){themeButton.addEventListener('click',(e)=>{e.preventDefault();const root=document.documentElement;if(root.getAttribute('data-theme')==='light'){root.removeAttribute('data-theme')}else{root.setAttribute('data-theme','light')}})}else{console.warn("No se encontró el botón con el ID 'themeButton'")}});document.addEventListener('DOMContentLoaded',()=>{const btnDestruir=document.getElementById('btn-destruir');if(!btnDestruir)return;let motorActivo=!1;const FISICA={rebote:0,friccion:0.4,friccionAire:0.02,gravedad:0.5};const selectoresGravedadEspecifica=`
        #visor-3d-container,
        .mainGrid__message,
        .mainGrid__about,
        #buttonForm,
        .mainGrid__another > ul,
        .footer_container div,
        #themeButton,
        .principal__about,
        .principal__social--cardIcon,
        .principal__social--card,
        #btn-destruir
    `;const selectoresHijosLibres=`
        .principal__about--img
    `;const fondosIntocables='.principal, .footer, .main, .principal--background, .backgroundLigth';btnDestruir.addEventListener('click',(e)=>{e.preventDefault();if(motorActivo)return;motorActivo=!0;const metaScroll=70;if(window.scrollY>metaScroll+10){window.scrollTo({top:metaScroll,behavior:'smooth'});const checarScroll=setInterval(()=>{if(window.scrollY<=metaScroll+5){clearInterval(checarScroll);iniciarCaos()}},100)}else{iniciarCaos()}});function iniciarCaos(){document.body.classList.add('gravedad-activada');const estiloCaos=document.createElement('style');estiloCaos.innerHTML=`
            .gravedad-activada * { 
                animation: none !important; 
                transition: none !important; 
                user-select: none !important;
                -webkit-user-select: none !important;
                -moz-user-select: none !important;
                -ms-user-select: none !important;
                -webkit-user-drag: none !important;
                outline: none !important;
            }
            .gravedad-activada a,
            .gravedad-activada span,
            .gravedad-activada label {
                display: inline-block !important;
            }
            .elemento-con-gravedad {
                pointer-events: none !important; 
            }
        `;document.head.appendChild(estiloCaos);const fondosParaCongelar=document.querySelectorAll(fondosIntocables);fondosParaCongelar.forEach(fondo=>{const rectFondo=fondo.getBoundingClientRect();if(rectFondo.height>0){fondo.style.setProperty('min-height',rectFondo.height+'px','important');fondo.style.setProperty('min-width',rectFondo.width+'px','important')}});const Engine=Matter.Engine,Runner=Matter.Runner,Bodies=Matter.Bodies,Composite=Matter.Composite,Mouse=Matter.Mouse,MouseConstraint=Matter.MouseConstraint,Query=Matter.Query;const engine=Engine.create();engine.world.gravity.y=FISICA.gravedad;const world=engine.world;const grosor=500;const largoMuro=10000;document.body.style.margin='0';document.body.style.padding='0';let ancho=document.documentElement.clientWidth;let alto=document.documentElement.clientHeight;const suelo=Bodies.rectangle(ancho/2,alto+grosor/2,largoMuro,grosor,{isStatic:!0});const techo=Bodies.rectangle(ancho/2,-grosor/2,largoMuro,grosor,{isStatic:!0});const paredIzq=Bodies.rectangle(-grosor/2,alto/2,grosor,largoMuro,{isStatic:!0});const paredDer=Bodies.rectangle(ancho+grosor/2,alto/2,grosor,largoMuro,{isStatic:!0});Composite.add(world,[suelo,techo,paredIzq,paredDer]);window.addEventListener('resize',()=>{ancho=document.documentElement.clientWidth;alto=document.documentElement.clientHeight;Matter.Body.setPosition(suelo,{x:ancho/2,y:alto+grosor/2});Matter.Body.setPosition(techo,{x:ancho/2,y:-grosor/2});Matter.Body.setPosition(paredIzq,{x:-grosor/2,y:alto/2});Matter.Body.setPosition(paredDer,{x:ancho+grosor/2,y:alto/2})});const nodos=document.querySelectorAll('*');const candidatos=[];const selectoresVisibles='p, img, span, a, button, input, textarea, h1, h2, h3, h4, h5, h6, label, svg, model-viewer';nodos.forEach(el=>{if(['BODY','HTML','HEAD','STYLE','SCRIPT','LINK','META'].includes(el.tagName))return;const esBloque=el.matches(selectoresGravedadEspecifica);let esHijoLibre=!1;if(selectoresHijosLibres.trim()!==''){try{esHijoLibre=el.matches(selectoresHijosLibres)}catch(e){}}
const padreGravedad=el.parentElement?el.parentElement.closest(selectoresGravedadEspecifica):null;if(padreGravedad){if(!esHijoLibre){return}}else if(!esBloque&&!esHijoLibre){if(el.matches(fondosIntocables)){el.style.setProperty('pointer-events','none','important');return}
if(!el.matches(selectoresVisibles))return;if(el.parentElement&&el.parentElement.closest(selectoresVisibles)){return}}
candidatos.push(el)});document.body.offsetHeight;const estilosClave=['color','background-color','background-image','font-family','font-size','font-weight','line-height','letter-spacing','text-align','border','border-radius','padding','box-shadow','fill','opacity','display','justify-content','align-items'];const precalculados=[];candidatos.forEach(el=>{const rect=el.getBoundingClientRect();if(rect.width===0||rect.height===0||rect.width>ancho*0.98)return;const computados=window.getComputedStyle(el);const estilosGuardados={};estilosClave.forEach(prop=>{estilosGuardados[prop]=computados.getPropertyValue(prop)});precalculados.push({el,rect,estilosGuardados})});const elementosSincronizados=[];precalculados.forEach(item=>{const{el,rect,estilosGuardados}=item;const anchoReal=rect.width;const altoReal=rect.height;let centroX=rect.left+anchoReal/2;let centroY=rect.top+altoReal/2;if(centroY>alto||centroY<0||centroX>ancho||centroX<0){centroX=Math.random()*(ancho-anchoReal)+(anchoReal/2);centroY=-(Math.random()*2500)-200}
const cuerpo=Bodies.rectangle(centroX,centroY,anchoReal,altoReal,{restitution:FISICA.rebote,friction:FISICA.friccion,frictionAir:FISICA.friccionAire});Composite.add(world,cuerpo);estilosClave.forEach(prop=>{if(estilosGuardados[prop]&&estilosGuardados[prop]!=='none'&&estilosGuardados[prop]!=='normal'){el.style.setProperty(prop,estilosGuardados[prop],'important')}});document.body.appendChild(el);el.style.setProperty('box-sizing','border-box','important');el.style.setProperty('width',anchoReal+'px','important');el.style.setProperty('height',altoReal+'px','important');el.style.setProperty('max-width','none','important');el.style.setProperty('max-height','none','important');el.style.setProperty('margin','0','important');el.style.setProperty('position','fixed','important');el.style.setProperty('top','0px','important');el.style.setProperty('left','0px','important');el.style.setProperty('transform-origin','center center','important');el.style.setProperty('z-index','9999','important');el.classList.add('elemento-con-gravedad');el.setAttribute('draggable','false');if(el.tagName==='MODEL-VIEWER'||el.querySelector('model-viewer')){const viewer=el.tagName==='MODEL-VIEWER'?el:el.querySelector('model-viewer');viewer.removeAttribute('camera-controls')}
elementosSincronizados.push({el,cuerpo,rect:{width:anchoReal,height:altoReal}})});const raton=Mouse.create(document.body);Matter.Mouse.setOffset(raton,{x:-window.scrollX,y:-window.scrollY});const interaccionRaton=MouseConstraint.create(engine,{mouse:raton,constraint:{stiffness:0.05,damping:0.1,angularStiffness:0,render:{visible:!1}}});Composite.add(world,interaccionRaton);let posXInicial=0;let posYInicial=0;Matter.Events.on(interaccionRaton,'mousemove',(event)=>{if(!interaccionRaton.body){const cuerpos=elementosSincronizados.map(v=>v.cuerpo);const cuerposBajoRaton=Query.point(cuerpos,event.mouse.position);document.body.style.cursor=cuerposBajoRaton.length>0?'grab':'default'}});Matter.Events.on(interaccionRaton,'mousedown',(event)=>{posXInicial=event.mouse.position.x;posYInicial=event.mouse.position.y});Matter.Events.on(interaccionRaton,'startdrag',()=>{document.body.style.cursor='grabbing'});Matter.Events.on(interaccionRaton,'enddrag',()=>{document.body.style.cursor='grab'});Matter.Events.on(interaccionRaton,'mouseup',(event)=>{const distanciaX=Math.abs(event.mouse.position.x-posXInicial);const distanciaY=Math.abs(event.mouse.position.y-posYInicial);const distanciaTotal=Math.hypot(distanciaX,distanciaY);if(distanciaTotal<5){const cuerpos=elementosSincronizados.map(v=>v.cuerpo);const cuerposBajoRaton=Query.point(cuerpos,{x:posXInicial,y:posYInicial});if(cuerposBajoRaton.length>0){const cuerpoClickeado=cuerposBajoRaton[0];const vinculo=elementosSincronizados.find(v=>v.cuerpo===cuerpoClickeado);if(vinculo){const botonReal=vinculo.el.closest('button, a, input, label, #themeButton, [id]')||vinculo.el;botonReal.click();const eventosAForzar=['mousedown','mouseup','click'];eventosAForzar.forEach(tipoEvento=>{const eventoSintetico=new MouseEvent(tipoEvento,{bubbles:!0,cancelable:!0,view:window});botonReal.dispatchEvent(eventoSintetico)})}}}});document.addEventListener('mouseleave',()=>{if(interaccionRaton.body){interaccionRaton.body=null;interaccionRaton.mouse.button=-1;document.body.style.cursor='default'}});Matter.Events.on(engine,'afterUpdate',()=>{elementosSincronizados.forEach(vinculo=>{const{el,cuerpo,rect}=vinculo;const posX=cuerpo.position.x-(rect.width/2);const posY=cuerpo.position.y-(rect.height/2);const angulo=cuerpo.angle;el.style.transform=`translate(${posX}px, ${posY}px) rotate(${angulo}rad)`})});document.body.style.overflow='hidden';Runner.run(Runner.create(),engine)}})
